# Generated by Django 6.0.6 on 2026-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
