# Generated by Django 6.0.6 on 2026-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
