# Generated by Django 6.0.6 on 2026-06-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_alter_doctor_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='patient_name',
        ),
    ]
