# Generated by Django 6.0.6 on 2026-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_rename_name_department_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
